from enum import Enum


class ConversationStage(str, Enum):
    GREETING = "GREETING"
    DISCOVERY = "DISCOVERY"
    PROFILING_COMPLETE = "PROFILING_COMPLETE"
    PROPOSAL = "PROPOSAL"
    OBJECTION = "OBJECTION"
    CONVERSION = "CONVERSION"
    ESCALATION = "ESCALATION"
    CLOSED = "CLOSED"
